blog/urls.py
from django.urls import path
from . import views

# from django.views.generic import TemplateView, RedirectView

app_name = "blog"

urlpatterns = [
    # path('fbv/', indexView, name="fbv-test"),
    # path('AUR-redirection/', RedirectView.as_view(url="https://aur.archlinux.org/"), name="aur-redirection"),
    # path('cbv2-redirection/', RedirectView.as_view(pattern_name="blog:cbv2-test"), name="cbv2-redirection"),
    # path('redirect-view/', views.redirectView, name="redirect-view"),
    # path('cbv/', TemplateView.as_view(template_name="index.html", extra_context={"name":"koth"}), name="cbv-test"),
    # path('post-redirection/<int:pk>/', views.RedirectViewAUR.as_view(), name="post-redirection-post"),
    path('cbv2/', views.IndexView.as_view(), name="cbv2-test"),
    path('aur-redirection/', views.RedirectViewAUR.as_view(), name="aur-redirection"),
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/<int:pid>/", views.PostDetailView.as_view(), name="post-detail-page"),
    path("post/create_temp/", views.PostFormView.as_view(), name="post-create"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create-form"),
    path("post/<int:pid>/update/", views.PostUpdateView.as_view(), name="post-update-page"),
    path("post/<int:pid>/delete/", views.PostDeleteView.as_view(), name="post-delete-page"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('blog/', include("blog.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
#from django.contrib.auth import get_user_model
#from accounts.models import Profile

#User = get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(default=False)    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField()
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "category", "status", "published_at"]

blog/views.py
from curses import A_VERTICAL
from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from .models import Post
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import PostForm
from django.urls import reverse_lazy

#Function Based View template show
'''def indexView(request):
    return render(request, "index.html")'''


# function based view redirect

'''def redirectView(request):
    return redirect("https://aur.archlinux.org/")'''
class IndexView(TemplateView):
    template_name = "blog/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = "koth2"
        context["age"] = 20
        context["city"] = "koth-city"
        context["posts"] = Post.objects.all()
        return context
    # extra_context = {"name":"koth2"}

class RedirectViewAUR(RedirectView):
    url = "https://aur.archlinux.org/"
    # permanent = True

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs["pk"])
        print(post.title)
        return super().get_redirect_url(*args, **kwargs)
        

class PostListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = "blog.view_post"
    model = Post
    context_object_name = "posts"
    paginate_by = 2
    ordering = ["-created_at"]

    #queryset = Post.objects.all()
    #template_name = "post_list.html"

    # def get_queryset(self):
    #     posts = Post.objects.filter(status=True)
    #     return posts

class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post_detail.html"

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs["pid"])

class PostFormView(FormView):
    form_class = PostForm
    template_name = "blog/post_form.html"
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    # fields = ["title", "content", "author", "category", "status", "published_at"] # or use form_class = PostForm instead of fields
    template_name = "blog/post_create.html"
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)

class PostUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = "blog.change_post"
    model = Post
    form_class = PostForm
    template_name = "blog/post_update.html"
    success_url = "/blog/post/"

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs["pid"])

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/post_delete.html"
    success_url = "/blog/post/"

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs["pid"])

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>koth</title>
</head>
<body>
    <p>
    i want koth
    koth is {{name}} my name
    </p>
    <p>
    age is {{age}}
    city is {{city}}
    </p>
    <p>
    posts are {{posts}}
    </p>
</body>
</html>

templates/blog/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Create</title>
</head>
<body>
    <h1>Post Create</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>

templates/blog/post_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Delete</title>
</head>

<body>
    <h1>Post Delete</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete?</button>
    </form>
</body>

</html>

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Detail</title>
</head>

<body>
    <h1>Post Detail</h1>
    <h2>title: {{ post.title }}</h2>
    <p>content: {{ post.content }}</p>
    <p>author: {{ post.author }}</p>
    <p>category: {{ post.category }}</p>
    <p>status: {{ post.status }}</p>
    <p>created_at: {{ post.created_at }}</p>
    <p>updated_at: {{ post.updated_at }}</p>
    <p>published_at: {{ post.published_at }}</p>
    <p>profile: {{ post.author.user }}</p>
    <p>email: {{ post.author.user.email }}</p>
    <p>first_name: {{ post.author.first_name }}</p>
    <p>last_name: {{ post.author.last_name }}</p>
</body>

</html>

templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Create temp</title>
</head>

<body>
    <h1>Post Create temp</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post List</title>
</head>

<body>
    <h1>Post List</h1>
    <ol>
        {% for post in posts %}
        <li>
            <h2>
                <a href="{% url 'blog:post-detail-page' pid=post.id %}">{{ post.title }}</a>
            </h2>
            <p>{{ post.content }}</p>
            <a href="{% url 'blog:post-update-page' pid=post.id %}">
                <h5>Update</h5>
            </a>
            <a href="{% url 'blog:post-delete-page' pid=post.id %}">
                <h5>Delete</h5>
            </a>
        </li>
        {% endfor %}
    </ol>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>

</html>

templates/blog/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Update</title>
</head>
<body>
    <h1>Post Update</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>